use Assignment

SELECT *
FROM EMP
WHERE JOB = 'MANAGER';

SELECT ENAME, SAL
FROM EMP
WHERE SAL > 1000;

SELECT ENAME, SAL
FROM EMP
WHERE ENAME <> 'JAMES';

SELECT *
FROM EMP
WHERE ENAME LIKE 'S%';

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%A%';

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__L%';

SELECT ENAME, SAL / 30 AS "Daily Salary"
FROM EMP
WHERE ENAME = 'JONES';

SELECT SUM(SAL) AS "Total Monthly Salary"
FROM EMP;

SELECT AVG(SAL) * 12 AS "Average Annual Salary"
FROM EMP;

SELECT ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30 AND JOB <> 'SALESMAN';

SELECT DISTINCT DEPTNO
FROM EMP;

SELECT ENAME AS Employee, SAL AS "Monthly Salary"
FROM EMP
WHERE SAL > 1500 AND (DEPTNO = 10 OR DEPTNO = 30);

SELECT ENAME, JOB, SAL
FROM EMP
WHERE (JOB = 'MANAGER' OR JOB = 'ANALYST') AND SAL NOT IN (1000, 3000, 5000);

SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM > SAL * 1.1;

SELECT ENAME
FROM EMP
WHERE (ENAME LIKE '%L%L%' AND DEPTNO = 30) OR MGR_ID = 7782;

SELECT ENAME
FROM EMP
WHERE DATEDIFF(YEAR, HIREDATE, GETDATE()) BETWEEN 30 AND 40;

-- To count the total number of employees:
SELECT COUNT(*)
FROM EMP
WHERE DATEDIFF(YEAR, HIREDATE, GETDATE()) BETWEEN 30 AND 40;

SELECT D.DNAME, E.ENAME
FROM DEPT D
LEFT JOIN EMP E ON D.DEPTNO = E.DEPTNO
ORDER BY D.DNAME ASC, E.ENAME DESC;

SELECT DATEDIFF(YEAR, HIREDATE, GETDATE()) AS "Experience (years)"
FROM EMP
WHERE ENAME = 'MILLER';

